In [1]:
import numpy.linalg as la
n=int(input())
l=[]
for i in range(n):
    col=[]
    for j in range(n):
        x=int(input(''))
        col.append(x)
    l.append(col)
print(l,'\n')
print("Determinant of Matrix=",la.det(l))
if(la.det(l)==0):
    print("\nThe matrix is SINGULAR so Invers is not Exist")
else:
    print("\nInvers of The Matrix=\n",la.inv(l))
print("\nRank of Matrix=",la.matrix_rank(l))
print('\nSqure of Matrix=\n',la.matrix_power(l,2))


3
1
2
3
4
3
5
1
2
1
[[1, 2, 3], [4, 3, 5], [1, 2, 1]] 

Determinant of Matrix= 9.999999999999998

Invers of The Matrix=
 [[-0.7  0.4  0.1]
 [ 0.1 -0.2  0.7]
 [ 0.5 -0.  -0.5]]

Rank of Matrix= 3

Squre of Matrix=
 [[12 14 16]
 [21 27 32]
 [10 10 14]]
